name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Instalar dependencias
        run: npm ci --legacy-peer-deps --no-audit --no-fund
      
      - name: Ejecutar linter
        run: npm run lint
      
      - name: Ejecutar tests
        run: npm test