name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Hello World
        run: echo "Hello World"
      
      - name: Mostrar fecha
        run: date
      
      - name: Listar archivos
        run: ls -la